### ISSUE TITLE
mindmap

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/project_G#3]
Is the mindmap for this in the onboarding or is it a new or updated idea?

**Comment by abaddonpuff** [comment]
This is the idea. I believe I sent an updated mindmap for this.

<img width="1168" alt="image" src="https://github.com/abaddonpuff/project_G/assets/25719314/aaea82b6-ec20-4136-833b-879e464f8835">

**Comment by bbelderbos** [comment]
Great idea, can you log a couple of issues? Specially the type of chat interaction will be useful to see if we go with Marvin AI now or maybe another NLP library ...

Thanks
Bob
